services:  # Servisler (Konteynerler) dizimi

  # 1-servis: Maǵlıwmatlar bazası (PostgreSQL)
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env


  web:
    build: .
    # Gunicorn iske túsedi
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles # Django usı jerge fayllardı jıynaydı (collectstatic)
      - media_volume:/app/media
    expose:
      - 8000 # Porttı tek ishki tarmaq (Nginx) ushın ashamız
    depends_on:
      - db
    env_file:
      - .env

  # JAŃA SERVIS: Nginx
  nginx:
    image: nginx:1.25-alpine # Jeńil Nginx versiyası
    ports:
      - "8003:80" # Sırtqı 80 porttı ishki 80 ge jalǵaw
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Sazlaw faylın ornatıw
      - static_volume:/home/app/web/staticfiles # Django jıynaǵan fayllardı oqıw
      - media_volume:/home/app/web/media
    depends_on:
      - web # Django iske túskennen keyin Nginx iske tússin

volumes:
  postgres_data:
  static_volume: # Ortaq statikalıq fayllar qutısı
  media_volume:



